# Workflow to Build & Deploy Toga
name: Build & Deploy Toga

# Triggers
on:
  # Runs on pushes targeting the default branch
   # Push a tag to run this workflow, ex: v0.0.1
  push:
    branches: ["main"]
    tags:
      - "v*.*.*"
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:

  # Build
  build:
    strategy:
      fail-fast: false
      matrix:
        # Build only for release configuration
        configuration: [Release]

    # For a list of available runner types, refer to
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: windows-latest                                                       
                                                                                    
    env:
      # Replace with your solution name, i.e. MyApp.sln.
      Solution_Name: TOGA.sln

      # Replace with the path to your project, i.e. MyApp.csproj.
      Project_Path: TOGA\TOGA.csproj

      # Workspace path where dotnet will publish the release build
      Workspace_Release_Build_Path: ${{ github.workspace }}\release\*

      # Workspace path where to create the zip of release build
      Workspace_Release_Build_Zip_Path: ${{ github.workspace }}\TOGA-${{ github.ref_name }}.zip

      # Workspace path of installer project i.e. MyApp.vdproj
      Workspace_Installer_Path: ${{ github.workspace }}\TOGASetup\TOGASetup.vdproj

      # Workspace path where devenv.com will publish the MSI Installer
      Workspace_Installer_Setup_Build_Path: ${{ github.workspace }}\TOGASetup\Setup\*

      # Workspace path where to create the zip of the msi installer
      Workspace_Installer_Setup_Build_Zip_Path: ${{ github.workspace }}\TOGASetup-latest.zip
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Setup GH Pages
    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v5

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    # Show Workspace Path
    - name: Workspace path
      run: echo 'Workspace path = ${{ github.workspace }}'

    # Publish release build of project
    - name: Publish
      run: dotnet publish $env:Project_Path -c Release -o release

    # Zip Release Build
    - name: Zip Release
      run: Compress-Archive -Path $env:Workspace_Release_Build_Path -Destination $env:Workspace_Release_Build_Zip_Path
          
    # Build MSI Installer
    - name: Setup VS Dev Environment
      uses: seanmiddleditch/gha-setup-vsdevenv@v4
    - name: Build installer
      run: devenv.com $env:Workspace_Installer_Path /Build "Setup"

    # Zip Release MSI Installer
    - name: Zip Release MSI Installer
      run: Compress-Archive -Path $env:Workspace_Installer_Setup_Build_Path -Destination $env:Workspace_Installer_Setup_Build_Zip_Path

    # Release artifacts
    - name: Release artifacts
      uses: softprops/action-gh-release@v2.2.2
      with:
          files: |
              ${{ github.workspace }}\TOGA-${{ github.ref_name }}.zip
              ${{ github.workspace }}\TOGASetup-${{ github.ref_name }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}

  # Deployment
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
